version: '3.8'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: dev
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev
    ports:
      - "4000:4000"
    networks:
      - telechat-net
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: dev
    env_file:
      - ./client/.env
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    networks:
      - telechat-net
    depends_on:
      - server
networks:
  telechat-net:
    driver: bridge
